### ISSUE TITLE
Optimize queries of the search field

### ISSUE THREAD

**Issue by Caligo77** [nicolas-van/lightningmf#6]
Hello , thank you for your work , he is useful with LXDE Desktop on Lubuntu . I'm testing your frontend on a very old machine , a Pentium 4 , 1.80 GH , and the number of roms analyzed is 1103 files . With this performance I would need that the search filter the search field departed after entering at least 4 characters , or alternatively , after a few seconds of the last character entered. Your frontend filters after each caratter inserted and 1103 files with the software slows down heavily : I have to wait a few seconds to enter a new character . You could optimize this situation by following my advice ? On old machines the situation should improve significantly , Thanks

P.S. Sorry for my bad english I hope I explained adequately

**Comment by nicolas-van** [comment]
I took a look at the current code and I saw multiple places that could be optimized. I released version 1.0.4 with these enhancements. Could you test that version to see if it's better? Re-open this issue if it's still too slow.

**Comment by Caligo77** [comment]
I upgraded using the command "sudo pip install lightningmf --upgrade" and it works. Now appears to be very much faster. With my old machine still has, however, a bit of latency during the insertion of the first three characters of the search string, if you want to further optimize this light just itching to start the search only after entering at least 4 characters as often happens in other software when you must filter a huge number of data. My though is an extreme case due to the slowness of my car and the huge number of roms analyzed but if you will do even this change, even in very old machine, your application will be very fast. If I add one other request, since I'm making a game machine for retrogaming, I need an icon for your frontend and can see the shortcut in the games section of Lubuntu. Now you can just create a custom shortcut on the desktop, but it is not easy to include an icon in the panel of LXDE Lubuntu, requires action by hand in the code of LXDE to add an icon to the interface. After installing the icon to appear in the games section of Lubuntu could easily include it in the main panel. Thanks again for your great work, I will contact you again if I find bugs and for more tips! Bye

**Comment by nicolas-van** [comment]
Version 1.0.5 may again be a *little* bit faster. But I don't plan to change it more as I like the application as it is: hyper responsive on normal computers.
