### ISSUE TITLE
With many snap, I think there are problems with the cache(?)

### ISSUE THREAD

**Issue by Caligo77** [nicolas-van/lightningmf#9]
Hi Nicolas,
I am using your frontend and I put all snap of mame, is a huge number: 26678 files. With such a large number of snap frontend tends to crash when you try to load the roms, even though they were very few roms. In practice, it should read only the snap useful to roms found to curb the problem.It builds up a huge cache useless and that creates problems on large numbers of snap.
If you then uninstall and reinstall the lightingmf cache not cleared and the problem persists, there is a stalemate.

You may correct?

Thanks for your great job!

Tiziano

**Comment by nicolas-van** [comment]
Hello,

LightningMF does not store all the roms info in the RAM. It saves them in a SQLite database. The program is optimized to never load too much information in the RAM. Having 26 000, 10 000 or 100 000 roms registered in MAME would not change anything, it would only take more time when you make a "Load ROM Data".

So, your interpretation of your problem is wrong. If you have a problem with the rom data stored by lightning, you can just erase the SQLite database by removing `~/.lightningmf/`.

Bye bye.

**Comment by Caligo77** [comment]
Maybe I explained myself wrong. I have a problem with a large number of snap. I have not added many roms, only 3, but I had put 126000 snap (all those of mame). I am using a virtual machine, and I set one gigabyte of RAM, if I put in the cache SQlite 126000 snap, lightingmf crashes. I think it should start erasing. Thank you

**Comment by nicolas-van** [comment]
That's not a problem either. LMF doesn't load the images in its database, it only checks if the image exists when it displays a game.

**Comment by Caligo77** [comment]
So I think that is just the updating phase of DB when there is a large number of snap to create problems with a low amount of RAM. I repeat, I put in 126000 files snap. Probably not an error but is simply a limit SQLite when writing large amounts of data but there is little ram. Tnx

**Comment by nicolas-van** [comment]
I just told you that the snaps are not in the DB.

**Comment by Caligo77** [comment]
Okay, I believe you. But not having read the code I can only speculate. But I do not understand what the resulting latency when loading 3 Roms and 126000 Snaps. This always happens to me lately and lihntingmf freezes, seems like it's in a loop. Simplify I'm telling you what happened to me.

**Comment by nicolas-van** [comment]
When you click on "Load ROM Data" LMF does **all** the data from MAME. This is independent on the number of files you have, but it can take a lot of time before it completes, potentially multiple minutes.

**Comment by Caligo77** [comment]
Ok, thanks for your support. If I wanted to advise you to "recycle" the code of lightingmf, to handle Vice, an emulator of the Commodore 64. There is still no one who has implemented a frontend to manage it under linux, you would like to develop it? Communities who love retrogaming would thank you very much.
